"""add_elo_rating_and_pvp_matches

Revision ID: 9370e4e59297
Revises: 5c55ccc61652
Create Date: 2026-02-02 11:10:44.909658

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9370e4e59297"
down_revision: Union[str, Sequence[str], None] = "5c55ccc61652"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pvp_matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player1_id", sa.Integer(), nullable=False),
        sa.Column("player2_id", sa.Integer(), nullable=False),
        sa.Column("player1_score", sa.Integer(), nullable=True),
        sa.Column("player2_score", sa.Integer(), nullable=True),
        sa.Column("player1_rating_before", sa.Integer(), nullable=False),
        sa.Column("player2_rating_before", sa.Integer(), nullable=False),
        sa.Column("player1_rating_after", sa.Integer(), nullable=True),
        sa.Column("player2_rating_after", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column(
            "tasks_used",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player1_id"],
            ["users.id"],
            name=op.f("fk_pvp_matches_player1_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["player2_id"],
            ["users.id"],
            name=op.f("fk_pvp_matches_player2_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pvp_matches")),
    )
    op.create_index(
        op.f("ix_pvp_matches_id"), "pvp_matches", ["id"], unique=False
    )
    op.add_column(
        "users", sa.Column("elo_rating", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "elo_rating")
    op.drop_index(op.f("ix_pvp_matches_id"), table_name="pvp_matches")
    op.drop_table("pvp_matches")
    # ### end Alembic commands ###
