"""add lecture_id to tasks

Revision ID: 1708453821d7
Revises: a6c9b4ba6e13
Create Date: 2026-01-29 00:07:50.778322

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1708453821d7"
down_revision: Union[str, Sequence[str], None] = "a6c9b4ba6e13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("lecture_id", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "tasks", "unit_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(
        op.f("fk_tasks_lecture_id_lectures"),
        "tasks",
        "lectures",
        ["lecture_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_tasks_lecture_id_lectures"), "tasks", type_="foreignkey"
    )
    op.alter_column(
        "tasks", "unit_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("tasks", "lecture_id")
    # ### end Alembic commands ###
