"""add user_task_progress table

Revision ID: 5c55ccc61652
Revises: 56147d377be0
Create Date: 2026-01-29 11:00:55.077476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c55ccc61652"
down_revision: Union[str, Sequence[str], None] = "56147d377be0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_task_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("user_answer", sa.Text(), nullable=True),
        sa.Column(
            "solved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_user_task_progress_task_id_tasks"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_task_progress_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_task_progress")),
    )
    op.create_index(
        op.f("ix_user_task_progress_id"),
        "user_task_progress",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_task_progress_id"), table_name="user_task_progress"
    )
    op.drop_table("user_task_progress")
    # ### end Alembic commands ###
