"""add lecture_id to tasks

Revision ID: 87068b97661e
Revises: 1708453821d7
Create Date: 2026-01-29 00:12:57.239087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87068b97661e"
down_revision: Union[str, Sequence[str], None] = "1708453821d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_tasks_unit_id"), "tasks", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_tasks_unit_id"),
        "tasks",
        ["unit_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
